name: Deploy to ECR

on:
 
  push:
    branches: [ main ]

# Any update to the helm files , It should auto update to K8s 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Update kube config
      run: aws eks update-kubeconfig --name EKS-CLOUD --region ${{ secrets.AWS_DEFAULT_REGION }}


# push to ECR 
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

# Docker build 
    
    - uses: actions/checkout@v2
    - uses: vitr/actions-build-and-upload-to-ecs@master
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: aws-ecr-repo
        region: ap-south-1
        tags: latest,${{ github.sha }}
        create_repo: true
    

    