apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  labels: 
    app: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: {{.Values.image.repository}}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000

