apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt-dev"
spec:
  ingressClassName: nginx
  rules:
  - host: sample.kubeace.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guestbook
            port:
              number: 3000
  tls:
  - hosts:
    - sample.kubeace.com
    secretName: sample-kubeace.com-tls